#!/usr/bin/env python

import fnmatch
import os


for dir in os.listdir('.'):
    if not dir.startswith('Set_'): continue
    if not os.path.exists(dir+'/GRID_ANALYSIS_lightchargedhiggs_default.root'):
        print dir

